"""
This type stub file was generated by pyright.
"""

from typing import override

from .caseconverter import DELIMITERS, CaseConverter

class Camel(CaseConverter):
    @override
    def define_boundaries(self) -> None: ...
    @override
    def prepare_string(self, s: str) -> str: ...
    @override
    def mutate(self, c: str) -> str: ...

def camelcase(s: str, *, delimiters: str = DELIMITERS, strip_punctuation: bool = True) -> str: ...
